### ISSUE TITLE
SSH & vnc not working

### ISSUE THREAD

**Issue by wassimdarwich** [EXALAB/AnLinux-App#107]
Hi: 
I have installed fedora distribution with their Desktop enviroment also SSH server
Fedora loaded successfully , my laptop ans my android phone are on same network and ping is available,  but i cant reach it by ssh it reject the connection directly , also vnc is connecting ok but with blank view only black ,please advice thanks

**Comment by exalab999** [comment]
It should be running fine by the normal case, Fedora VNC does require to wait around some seconds for it to show, for the SSH Server, you would likely need to create a new user and connect with it, since most SSH Client does not support root user connection.

**Comment by wassimdarwich** [comment]
hi thanks for your reply
I waited foe more than 10 minutes and vnc shows only black screen  also for ssh its not  a user thing , cause its not doing connection at all "connection refused"
I also use putty and juicessh which they use a "root" as user  , and also tried to adduser and tried to connect with the new user also no success any ideas

**Comment by exalab999** [comment]
Thanks for reporting the bug, Xfce4 should been fixed now, run this command to update it: `vncserver-stop && rm -f ~/.vnc/xstartup && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/DesktopEnvironment/Apt/Xfce4/xstartup -P ~/.vnc/` Then you could run `vncserver-start`, it should run normally now.

As for the ssh server, currently there are no bugs after inspection. Did you run `/etc/init.d/sshd start` before connect? Or did you encounter any error during installation?

**Comment by wassimdarwich** [comment]
Bug didnt fix the issue,  vnc still blank ,
For ssh no error during ssh installation but i executed "etc/init.d/sshd start" and thats whtve got :
 bash: /etc/init.d/sshd: No such file or directory
But the wierd thing that ssh is working from inside tried to ssh my linux server and was ok ,but from outside it rejects  , i have ssh tested with debian(vnc worked fine)  and centos also reject.

**Comment by exalab999** [comment]
Hmm... This is weird, if you following the guide inside the app, the sshd should be there, did you install the DE and ssh manually or using in app guide?

**Comment by wassimdarwich** [comment]
Using app in guide 
, iam able to connect other linux server through ssh , that means ssh is working ok , but iam Not able to reach or answer external connections ,tried from windows using putty also from app juicessh so its locally also connection refuse

**Comment by wassimdarwich** [comment]
This problem is also happening with Debian

**Comment by exalab999** [comment]
Sorry for the typo, actually the command is `/etc/init.d/ssh start`, not `etc/init.d/sshd start`, but please note that connect to this SSH Server from external device require Root Access, so you would be able to connect on same phone only.

**Comment by bpsib** [comment]
I think the problem could be because the SSH Server is configured to listen on a port below 1024 (22 by default). These are called privileged ports so root access is needed. Try changing the port in the sshd_config file to something above 1024 (e.g. 2222). You should then be able to connect from external device. Use the `-p <port>` option in the ssh command to specify the port on the client.

**Comment by gokaybiz** [comment]
In fedora there is no init scripts in /etc/init.d/
Same issue here. What can we do about that?
Also we can't use systemctl.

**Comment by RuofengX** [comment]
It seems like that the ssh-apt.sh script for fedora gpt something wrong. Im running ubuntu on my termux and changing the default port in sshd_config to 8022 is work. Also I have the "ssh" file in /etc/init.d
So I guess there's something wrong with fedora's ssu script. (I didnt try fedora ever)
